name: CI
on: [ push ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ secrets.PATH }}
            git pull
            git checkout ${{ github.ref_name }}
            git fetch
            git pull
            source ./venv/bin/activate
            pip install -r requirements.txt
            pm2 restart pzio
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
